export const languages = {
  text: ['plain', 'log'],
  config: ['yaml', 'json', 'xml', 'ini'],
  code: [
    'java',
    'javascript',
    'typescript',
    'python',
    'kotlin',
    'scala',
    'cpp',
    'csharp',
    'shell',
    'ruby',
    'rust',
    'sql',
    'go',
    'lua',
    'swift',
    'c',
  ],
  web: ['html', 'css', 'scss', 'php', 'graphql'],
  misc: ['diff', 'dockerfile', 'markdown', 'proto'],
};

export const fileExtensions: { [key: string]: string } = {
  plain: 'txt',
  log: 'log',
  yaml: 'yaml',
  json: 'json',
  xml: 'xml',
  ini: 'ini',
  java: 'java',
  javascript: 'js',
  typescript: 'ts',
  python: 'py',
  kotlin: 'kt',
  scala: 'scala',
  cpp: 'cpp',
  csharp: 'cs',
  shell: 'sh',
  ruby: 'rb',
  rust: 'rs',
  sql: 'sql',
  go: 'go',
  lua: 'lua',
  swift: 'swift',
  c: 'c',
  html: 'html',
  css: 'css',
  scss: 'scss',
  php: 'php',
  graphql: 'graphql',
  diff: 'diff',
  dockerfile: 'dockerfile',
  markdown: 'md',
  proto: 'proto',
};
